#!/bin/bash

music(){
title="$(ncmpcpp --now-playing "{%t}|{%f}")"
time="$(mpc -f "%position%" | awk 'NR==2 {print $3}')"
STATUS="$(mpc status | awk 'NR==2 {print $1}' | sed 's/^.\{,1\}//' | sed 's/.\{1\}$//')"
if [[ $STATUS ==  playing ]]; then
	echo -e "\x02æ\x01$title\x14 $time\x01"
elif  [[ $STATUS == paused ]]; then 
	echo -e "\x03ç\x01$title\x14 $time\x01"
else 
	echo -e ""
fi
}

cpu(){
        read cpu a b c previdle rest < /proc/stat
        prevtotal=$((a+b+c+previdle))
        sleep 0.5
        read cpu a b c idle rest < /proc/stat
        total=$((a+b+c+idle))
        cpu="$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))"
        echo -e "\x0FÑ\x01$cpu%"
}

cputemp(){
	temp="$(acpi -t | awk '{print $4}' | sed 's/.\{2\}$//')"
	echo -e "\x03$temp°c\x01"
}

hdd(){
	hd="$(df -hlT / | awk 'NR==2 {print $4}'| sed 's/.\{1\}$//')"
	echo -e "\x0F¨\x01$hd GB\x01"
}

mem(){
        mem="$(awk '/^-/ {print $3}' <(free -m))"
        echo -e "\x0FÎ\x01$mem MB\x01"
}

netdown(){
	netdown="$(ifconfig | awk 'NR==13 {print $6,$7}' | sed 's/^.\{,1\}//' | sed 's/.\{1\}$//')"
	if [ -z "$netdown" ]; then
	echo -e "\x01"
	else
	echo -e "\x0FÝ\x01$netdown"
	fi
}

netup(){
	netup="$(ifconfig | awk 'NR==15 {print $6,$7}' | sed 's/^.\{,1\}//' | sed 's/.\{1\}$//')"
	if [ -z "$netup" ]; then
	echo -e "\x05No Internet\x01"
	else
	echo -e "\x0FÜ\x01$netup"
	fi
}

vol(){
	op1="$(amixer get Master| awk 'NR==6 {print $5}'| sed 's/^.\{,1\}//' | sed 's/.\{1\}$//')"
	op2="$(amixer get Master| awk 'NR==6 {print $6}'| sed 's/^.\{,1\}//' | sed 's/.\{1\}$//')" 
	head="$(cat /proc/asound/card0/codec#0 | grep Power-Map | awk '{print $2}' | sed 's/^.\{,3\}//')"
	if [[ $op2 == on && $head == 0 ]]; then
		echo -e "\x0Fà\x01$op1"
	elif [[ $op2 == on && $head == 1 ]]; then
		echo -e "\x0Fí\x01$op1"
	else
		echo -e "\x0Fë\x01Mute"
	fi
}

dte(){
        dte="$(date "+%a %d %b %I:%M %p")"
        echo -e "\x0FÉ\x01$dte"
}

power(){
adapter="$(acpi -V | awk 'NR==3 {print $3}' | sed 's/.\{5\}$//')"
battery="$(acpi -V | awk 'NR==1 {print $4}' | sed 's/.\{1\}$//')"

	if [[ $adapter == on ]]; then
		echo -e "\x0FÂ\x01AC"
	else 
		echo -e "\x05ï\x01BAT:$battery"
	fi
}

# Status bar
xsetroot -name "$(music) $(cpu)$(cputemp) $(hdd) $(mem) $(netdown) $(netup) $(vol) $(dte) $(power)"
