#!/bin/bash
while true; do
FILE="$( grep 'DNS' /tmp/wvdial.out)"
  if [ -n "$FILE" ]; then
	notify-send "Successfully Connected."
	exit 0
  elif [ -z "$FILE" ]; then
	bash /home/garry/.scripts/internet
	exit 0
  fi
done
