#!/bin/bash
#
# Script to optimize Archlinux mirrors by speed and sync status
# Author: Gaurav Trivedi
#

if [[ $EUID -ne 0 ]]; then
echo "This script must be run as root" 1>&2
exit 1
fi

function progress {
  chars=( "-" "\\" "|" "/" )
  interval=0.2
  count=0

  while true
  do
    pos=$(($count % 4))
    echo -en "\b${chars[$pos]}"
    count=$(($count + 1))
    sleep $interval
  done
}


function stop_progress {
  exec 2>/dev/null
  kill $1
  echo -en "\bdone!\n"
}


function halt_progress {
  exec 2>/dev/null && cp /etc/pacman.d/mirrorlist.bak /etc/pacman.d/mirrorlist 
  kill $1
  echo -e "\nTerminated by user\nRestored mirrorlist from backup\nFor more information visit: https://wiki.archlinux.org/index.php/Mirror"
}

echo -e "Backing up existing mirrorlist..."
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak

echo -n "retrieving latest mirrorlist...."
progress &
pid=$!

trap 'halt_progress $pid; exit' 2
/usr/bin/reflector -l 10 --sort rate --save /etc/pacman.d/mirrorlist.temp


echo -ne "\bdone!\n"
echo -en "sorting mirrors by speed...."


rankmirrors -n 5 /etc/pacman.d/mirrorlist.temp > /etc/pacman.d/mirrorlist

stop_progress $pid

echo -e "\nFor more information visit: https://wiki.archlinux.org/index.php/Mirror"
