#!/bin/bash
echo "" > /tmp/wvdial.out
IPTAB="$(systemctl status iptables.service | awk 'NR==3 {print $2}')"
FILE="$( grep 'DNS' /tmp/wvdial.out)"
  if [[ $IPTAB == inactive ]]; then
    notify-send "Activating Firewall..."
    sudo systemctl start iptables.service &&
    notify-send "Firewall Activated. Dialing Modem..."
    sudo wvdial > /tmp/wvdial.out 2>&1 &
    /home/garry/.scripts/internet

elif [[ $IPTAB == active ]]; then
	notify-send "Firewall already active. Dialing Modem..."
	sudo wvdial > /tmp/wvdial.out 2>&1 &
	/home/garry/.scripts/internet
fi
