#! /bin/bash
WALLPAPERS="/home/garry/Pictures"
#ALIST=( `ls -w1 $WALLPAPERS` )
ALIST=( `ls -l $WALLPAPERS | grep -v ^d | awk '{print $9}'` )
RANGE=${#ALIST[@]}
let "number = 1"
let LASTNUM="`cat $WALLPAPERS/.last` - $number"
let "number = $LASTNUM % $RANGE"
echo $number > $WALLPAPERS/.last
##nitrogen --set-scaled --save $WALLPAPERS/${ALIST[$number]}
feh --bg-fill $WALLPAPERS/${ALIST[$number]}
