#!/bin/bash
# Start some nice programs for DWM
#
#/home/garry/.scripts/rotatewallpaper
sh .fehbg
dropboxd &
xset r rate 350 50 
#conky | while read -r; do xsetroot -name "$REPLY"; done &
conky -c /home/garry/.conkyrc2 &
conky -c /home/garry/.conkyrc3 &
numlockx on &
while true; do
/home/garry/.scripts/dwmstatus
sleep 0.5
done &
while true; do
dwm || exit
done
