#!/bin/bash
ActiveWinID=$(xdotool getwindowfocus)						## Get current focused window
WindowIDS=$(xdotool search --class "Thunar")					## Get all thunar windows ids
for WinID in $WindowIDS
do
    if [ "$WinID" == "$ActiveWinID" ];then
        echo "Found active thunar window."
        xdotool key --window "$ActiveWinID" --clearmodifiers "Ctrl+l"		## Get thunar pathbar
	xdotool key --window "$ActiveWinID" --clearmodifiers "Shift_L+Tab"	## Return to where we were in thunar
        Location=$(xclip -o -selection "primary")				## Copy the path to variable
            urxvtc -cd "$Location" &						## Open terminal in location
    fi
done
echo "Thunar window was not active. Aborting."
exit 1
