#!/bin/bash
ActiveWinID=$(xdotool getwindowfocus)						## Get current focused window
WindowIDS=$(xdotool search --class "Thunar")					## Get all thunar windows ids
## Check whether the active window id actually belongs to a thunar window or not
for WinID in $WindowIDS
do
    ## If activewindow is same as thunar window, then
    if [ "$WinID" == "$ActiveWinID" ];then
        echo "Found active thunar window."
        xdotool key --window "$ActiveWinID" --clearmodifiers "Ctrl+l"		## Get thunar pathbar
        #xdotool key --window "$ActiveWinID" --clearmodifiers "Ctrl+c"		## Copy thunar directory path to clipboard (needed when "pathbar style" in thunar is active)
        #xdotool key --window "$ActiveWinID" --clearmodifiers "Return"		## Should remove the pathbar if selected (needed when "pathbar style" in thunar is active)
	xdotool key --window "$ActiveWinID" --clearmodifiers "Shift_L+Tab"	## Return to where we were in thunar
        Location=$(xclip -o -selection "primary")				## Copy the path to variable
            urxvt -cd "$Location" &						## Open terminal in location
    fi
done
echo "Thunar window was not active. Aborting."
exit 1
