#! /bin/bash
WALLPAPERS="/home/garry/Pictures/"
#ALIST=( `ls -w1 $WALLPAPERS` )
ALIST=( `ls -l $WALLPAPERS | grep -v ^d | awk '{print $9}'` )
RANGE=${#ALIST[@]}
let "number = 1"
case "$1" in
	next) let LASTNUM="`cat $WALLPAPERS/.last` + $number" ;;
	prev) let LASTNUM="`cat $WALLPAPERS/.last` - $number" ;;
	esac
let "number = $LASTNUM % $RANGE"
echo $number > $WALLPAPERS/.last
feh --bg-fill $WALLPAPERS/${ALIST[$number]} 
